### ISSUE TITLE
Space occupation problem

### ISSUE THREAD

**Issue by tiandiyixian** [scanoss/engine#18]
When generating code index data, a small project will generate a large amount of data, almost a few G, is there any way to compress the data, it is acceptable for small project samples, but the number of lines of code is large , It takes up too much space。

**Comment by mscasso-scanoss** [comment]
Hi @tiandiyixian , thank you for your question.

The LDB database is meant to store very large amounts of data. There is a high overhead otherwise if you intend to use them with small data sets. An empty table takes a few Gb which becomes insignificant when storing terabytes of data. This is because the LDB creates hash maps, avoiding the use of indexes.

**Comment by tiandiyixian** [comment]
thanks !
