### ISSUE TITLE
Is it possible to ignore comment?

### ISSUE THREAD

**Issue by leoliaolei** [scanoss/engine#43]
It seems the comments in Java and C are included in the similarity detection. It is possible to ignore all comments when do the comparing?

**Comment by mscasso-scanoss** [comment]
While we don't have a ready-made solution to ignore comments, there are multiple ways to address this, depending on your actual need:
- To ignore all comments: Ignore comments when calculating wfp fingerprints. This will prevent those fingerprints to be sent to the backend and, therefore. I would be careful with this approach since comments could be very useful when finding real matches. This could be a CLI feature
- To ignore some comments: The first option is to ignore certain strings when calculating wfp fingerprints. Another option would be to build a database of unwanted wfps, and filter them out with some wrapper on the client side. This requires requesting snippet IDs when scanning
- To add some comments to the ignorelist: If you have identified comments that are not interesting and you consider it should be ignored always for everyone, please provide these comments and we add them to the IGNORED_WFP blob here: https://github.com/scanoss/minr/blob/master/src/ignored_wfp.c

**Comment by leoliaolei** [comment]
@mscasso-scanoss Thanks a lot for the details. 

In my case, user does not care about the comment similarity. I tried approach one (to ignore call comments) . Firstly download source code to local files. Then remove comments with a shell script and run the minr on local files. This removes comments but it also removes comments in the .mz source code. 

Is there some way to keep comments in .mz source archives, but remove comments for fingerprinting?

**Comment by mscasso-scanoss** [comment]
Hi @leoliaolei Sorry for the delay. Maybe you want to try HPSM ([High Precision Snippet Matching](https://github.com/scanoss/hpsm). You can use HPSM as shared library with scanoss command to get an accurate line range.  So, in your application, when the scanned files will be compared with the source file clean from comments you will get a matching line rage excluding the comments.
