### ISSUE TITLE
Request for clarification about disclosure of file names

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/engine#76]
Documentation on the .wfp file says that the filename, line number, and fingerprint are there. For example:

```
file=34cff02ed13a3d26e716e473d4e8900d,test.c
3=688c09fe,fc6d701d,61b2b37c
```

Does this mean file names are transmitted to the remote index server, such as the public ScanOSS API server?

**Comment by juliancoccia** [comment]
Yes, file names are transmitted to our API. They are used as keys in the JSON response, allowing for multiple files per request.

However, our backend is entirely stateless, which means no data is retained on our servers after processing. This design ensures privacy and efficiency.

We believe in full transparency, which is why our entire backend is open source, allowing anyone to review the code and verify our data handling practices.

Nevertheless, our client applications include an option to obfuscate file names. While this enhances privacy, it may slightly reduce matching precision, as file paths and names provide useful context for the scanning process.

For users with specific security requirements, self-hosted deployments of our backend are possible. This approach keeps all data and processing within your own infrastructure, addressing any concerns about data transmission to external services.​​​​​​​​​​​​​​​​

As an open-source project, we welcome contributions and feedback from the community to continually improve our system's security, efficiency, and functionality.

**Comment by lucasgonze** [comment]
Could you say more about how the file name is used to provide context for matching? Before I recommend to my client that the option to obfuscate names be enabled, I need to be able to explain the tradeoffs.

Even just pointing me to the relevant source code would be fine.

**Comment by mscasso-scanoss** [comment]
Hi @lucasgonze, it will be my pleasure to clarify this matter for you. While there are some special features that use the file name as part of the engine best match selection logic, this is not part of our standard services and is not mandatory.

You can test the obfuscation feature with our free and open Python client by running:
```
scanoss-py fp --obfuscate some_file_or_folder > some_file_or_folder.wfp
```
and then:
```
scanoss-py scan -w some_file_or_folder.wfp
```
If you check the content of `some_file_or_folder.wfp`, you will see that the file names are obfuscated.

Do not hesitate to ask any further questions. Best regards,
Mariano Scasso

**Comment by lucasgonze** [comment]
Mariano, thank you very much. I will recommend this approach to the client, which is concerned about potential information leaks.
