### ISSUE TITLE
[5.4.8]  use minr2.5.11 ldb4.1.4 unable to scan results

### ISSUE THREAD

**Issue by CharmNight** [scanoss/engine#80]
Use engine 5.4.8 + minr 2.5.11 + ldb4.1.4 scan snippets . 
unable to scan results.  but use engine version 5.3.1, I can scan results. 

initialize_ldb_tables  method , there is a change in the parameter used to initialize oss_wfp. How Do I upgrade

**Comment by mscasso-scanoss** [comment]
Hi @CharmNight, thank you for reporting this issue.

The problem you're experiencing is likely related to importing the mined CSVs using minr instead of ldb. Starting from version 4 onwards, ldb supports the import process through the "bulk insert command". This process updates the ldb tables (in /var/lib/ldb/oss) and creates new configuration files in the same location. Additionally, you'll find logs and a global configuration file in "/usr/local/scanoss/ldb".

To ensure the engine can read the tables correctly, please check the files inside /var/lib/ldb/oss. You should have a ".cfg" file for each folder.

Below is the expected content for each configuration file. Please create any missing files or update existing ones if their content differs:

file.cfg:
```
16,0,2,0
```

url.cfg:
```
16,0,1,0
```

wfp.cfg:
```
4,18,1,0
```

notices.cfg:
```
16,0,1,2
```

sources.cfg:
```
16,0,1,2
```

purl.cfg:
```
16,0,1,0
```

cryptography.cfg:
```
16,0,1,0
```

license.cfg:
```
16,0,1,0
```

quality.cfg:
```
16,0,1,0
```

Please let me know if updating this configuration files the issue is solved. Best regards,

Mariano Scasso
Core Software Engineer

**Comment by CharmNight** [comment]
Thanks for solving my problem.
But I have a question.
When I use it. /scanoss-k: Encoder lib not available. Install Libscanoss. So and try again
How should I get libscanoss.

**Comment by CharmNight** [comment]
1. /var/lib/ldb/oss/sources only files ending in mz.

2. when i try to add `sources.cfg` , The error message is still displayed .

```
root@codeforce-PC:/mnt/hgfs/ldb-core#  ./scanoss -k 558c6906a9c6ea1f03da672dacda2455 -p /mnt/hgfs/ldb-core/ldb
Encoder lib not available. Install libscanoss_encoder.so and try again
root@codeforce-PC:/mnt/hgfs/ldb-core# ls ./ldb/oss/
attribution  attribution.cfg  copyright  copyright.cfg  cryptography  cryptography.cfg  file  file.cfg  license  license.cfg  notices  quality  quality.cfg  sources  sources.cfg  url  url.cfg  version.json  wfp  wfp.cfg
root@codeforce-PC:/mnt/hgfs/ldb-core# cat ldb/oss/sources.cfg 
16,0,1,2
```
